colorScheme = "forest"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "posts" ]

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/blowfish_lite/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email" ]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = true

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]
